#!/usr/bin/env node

'use strict';

let program = require( 'commander' );
const pkg = require( './package' );
const fs = require( 'fs' );
const validator = require( './src/validator' );

const _getFileContents = filePath => {
    return new Promise( ( resolve, reject ) => {
        fs.readFile( filePath, 'utf8', ( err, xform ) => {
            if ( err ) {
                if ( err.code === 'ENOENT' ) {
                    err = `File: ${filePath} does not exist.`;
                }
                reject( err );
            } else {
                resolve( xform );
            }
        } );
    } );
};

const _output = ( issues = [], error = false ) => {
    if ( issues.length ) {
        console[ error ? 'error' : 'log' ]( `\n\n${issues.join( '\n\n' )}` );
    }
};

program
    .usage( '[options] <file>' )
    .version( pkg.version )
    .option( '-m, --me', 'get personal validation' )
    .option( '-d, --debug', 'output raw errors' )
    .option( '-o, --oc', 'run additional custom OpenClinica validation rules and use a custom XPath evaluator' )
    .parse( process.argv );

const xformFile = program.args[ 0 ];
const options = { debug: program.debug, openclinica: program.oc };

if ( program.me ) {
    console.log( 'You are correct.\nYour feelings matter.\nYou are wonderful and the world is better with you in it.' );
    process.exit( 0 );
} else if ( xformFile ) {
    console.log( `Enketo validating ${xformFile}` );

    _getFileContents( xformFile )
        .then( xformStr => validator.validate( xformStr, options ) )
        .catch( ( errors = [] ) => {
            errors = Array.isArray( errors ) ? errors : [ errors ];
            _output( errors, true );
            process.exit( 1 );
        } )
        .then( ( result = {} ) => {
            _output( result.warnings );
            _output( result.errors, true );

            if ( result.errors.length ) {
                _output( [ options.openclinica ? '' : 'Result: Invalid\n\n' ], true );
                process.exit( 1 );
            } else {
                _output( [ options.openclinica ? '' : '>> XForm is valid! See above for any warnings.\n\n' ] );
                process.exit( 0 );
            }
        } );

} else {
    console.error( 'Nothing to do. No XForm File provided. Use --help flag to see manual.' );
    process.exit( 1 );
}
